### ISSUE TITLE
App loads only a small map area.

### ISSUE THREAD

**Issue by JSzut** [sothawo/mapjfx-demo#2] opened 2018-03-28 14:13 UTC
Why does demo app map load only small parts and the loading lasts very long (my internet connection is fine)?

**Comment by sothawo** [comment] 2018-03-28 19:08
I know this is a problem, please see this post: https://www.sothawo.com/2018/02/mapjfx-problems/
Alas there is nothing I can do at the moment, because is not reproducible.

**Comment by sothawo** [comment] 2019-02-15 18:34
closing this as this is already in the library repo [https://github.com/sothawo/mapjfx/issues/29](https://github.com/sothawo/mapjfx/issues/29)

**Closed by sothawo** 2019-02-15 18:34 UTC
